version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app   # Mount the entire project into /app
      - fastf1cache:/tmp/fastf1cache  # Persist FastF1 cache
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: f1
      POSTGRES_PASSWORD: f1
      POSTGRES_DB: f1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  fastf1cache:
